name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Angular project
        run: npm run build -- --base-href=https://kayYZ1.github.io/angular-interactive-map/

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/angular-interactive-map
